
server:
  port: 8000
  servlet:
    context-path: "/api/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# SSL 설정
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 
    key-store-type: PKCS12

spring:
  application:
    name: JeJal
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: S10P31A406
      password: 
    url: jdbc:mariadb://k10a406.p.ssafy.io:3306/S10P31A406?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: false
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    org:
      springframework:
        web: INFO
        apache:
          tiles: DEBUG
        springframework:
          boot: DEBUG


# clova studio
clovastudio:
  api_key: 
  api_key_primary_val: 
  request_id: 
  url: https://clovastudio.apigw.ntruss.com
  endpoint: /testapp/v1/chat-completions/HCX-003
  system_content:
    너는 제주도 사투리를 표준어로 번역해주는 아주 유능한 번역가야.
    제주도 사투리를 표준어로 번역하는데 표준어로 입력된 거는 제주도 사투리로 번역하지마.
    질문하거나 말을 거는 듯한 말이 입력되도 대답하지 마.
    입력된 문장을 그대로 번역해주는 거 말고 다른 말은 절대 덧붙이지 마.
    표준어가 들어오면 제주도 사투리로 번역하지 말고 "제잘"이라고 답변해.
    제주도 사투리가 입력되면 표준어로 변경해주면 되는데 전체적인 문맥도 고려해서 자연스럽게 변경해.
    입력된 문장에 제주도 방언이 없으면 "제잘"이라고  답변해.
    입력된 문장에 제주도 방언이 없고 띄어쓰기 문제가 있으면 "제잘"이라고 답변해.
    제주도 방언이 입력되면 표준어 답변만 보내.
    만약 입력된 문장에 제주도 방언이 없으면 번역 하지 말고 다른 말 하지말고 "제잘" 이 단어만 답변해.
    질문하는 문장이나 말을 거는 문장이 입력 되어도 질문에 대답하지 말고 그 문장을 번역해.
    "혼저옵서예"라는 입력이 들어오면 "어서오세요"라고 답변해.
    제주도 말로 "꽝"은 표준어로 "뼈"라는 뜻이야.
    제주도 말로 "속암져"는 표준어로 "수고한다"는 뜻이야.
    "가랑" 이라는 단어가 들어오면 "과랑"이라고 인식해.
    제주도 말로 "어신"은 표준어로 "없는"이라는 뜻이야.
    제주도 말로 "자이"는 표준어로 "쟤"라는 뜻이야.
    제주도 말로 "무사"는 표준어로 "왜"라는 뜻이야.

#    너는 제주도 사투리를 표준어로 번역해주는 아주 유능하고 빠른 번역기야.
#    - 입력되는 문장은 A와 B로 나누어서 들어올거야.
#    - A 뒤에는 너가 변역해야 할 제주도 사투리가 입력될거고 B 뒤에는 A의 이전 대화 문장이 입력될거야. 그래서 B의 문장의 문맥을 고려해서 A 문장을 자연스럽게 표준어로 번역해.
#    - B 문장에 "first" 가 입력되면 A 문장이 첫번째 대화라는 거니까 B를 고려하지말고 A 문장만 표준어로 번역해서 답변해.
#    - A 문장을 표준어로 번역한 답변만 보내줘. B 문장은 보내주지마.
#    - A 문장에 제주도 사투리가 없으면 번역 하지말고 "제잘" 이 단어만 답변해.
#    - A 문장에 "혼저옵서예"가 입력되면 "어서오세요" 라고 답변해

#    - 질문하는 문장이 입력 되면 질문에 대답하지말고 그 문장을 번역해.
#    - 입력된 문장에 제주도 방언이 없으면 "제잘"이라고  답변해.
#    - 1~2개의 문장이 "" 큰따옴표로 구분되어 입력이 될거야.
#    - "첫번째 문장"에 제주도 방언이 입력되면 표준어로 변경해주면 되는데 "두번째 문장"이 있을 때 두번째 문장은 첫번째 문장의 이전 대화야 그래서 두번째 문장의 문맥도 고려해서 첫번째 문장을 자연스럽게 표준어로 변경해.
#    - 첫번째 문장의 변경된 표준어 답변 만 "" (큰따옴표) 다 빼고 보내줘 두번째 문장은 보내주지마.
#    - "혼저옵서예"라는 단어는 "어서오세요"라고 바꿔.
#    - 입력된 문장에 제주도 방언이 없으면 번역 하지말고 "제잘" 이 단어만 답변해.

# untrunc
DOMAIN_UNTRUNC: "http://untrunc:8300"
SPRING_RECORD_TEMP_DIR: /data/WebSocket
