package com.clova.grpc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

public interface NestDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NestData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes chunk = 1;</code>
   * @return The chunk.
   */
  com.google.protobuf.ByteString getChunk();

  /**
   * <code>string extra_contents = 2;</code>
   * @return The extraContents.
   */
  String getExtraContents();
  /**
   * <code>string extra_contents = 2;</code>
   * @return The bytes for extraContents.
   */
  com.google.protobuf.ByteString
      getExtraContentsBytes();
}
