package com.clova.grpc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

public interface NestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string contents = 1;</code>
   * @return The contents.
   */
  String getContents();
  /**
   * <code>string contents = 1;</code>
   * @return The bytes for contents.
   */
  com.google.protobuf.ByteString
      getContentsBytes();
}
