package com.clova.grpc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

/**
 * Protobuf type {@code NestData}
 */
public final class NestData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NestData)
    NestDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NestData.newBuilder() to construct.
  private NestData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NestData() {
    chunk_ = com.google.protobuf.ByteString.EMPTY;
    extraContents_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new NestData();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NestData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            chunk_ = input.readBytes();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            extraContents_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Nest.internal_static_NestData_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Nest.internal_static_NestData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NestData.class, Builder.class);
  }

  public static final int CHUNK_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString chunk_;
  /**
   * <code>bytes chunk = 1;</code>
   * @return The chunk.
   */
  @Override
  public com.google.protobuf.ByteString getChunk() {
    return chunk_;
  }

  public static final int EXTRA_CONTENTS_FIELD_NUMBER = 2;
  private volatile Object extraContents_;
  /**
   * <code>string extra_contents = 2;</code>
   * @return The extraContents.
   */
  @Override
  public String getExtraContents() {
    Object ref = extraContents_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      extraContents_ = s;
      return s;
    }
  }
  /**
   * <code>string extra_contents = 2;</code>
   * @return The bytes for extraContents.
   */
  @Override
  public com.google.protobuf.ByteString
      getExtraContentsBytes() {
    Object ref = extraContents_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      extraContents_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!chunk_.isEmpty()) {
      output.writeBytes(1, chunk_);
    }
    if (!getExtraContentsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, extraContents_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!chunk_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, chunk_);
    }
    if (!getExtraContentsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, extraContents_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NestData)) {
      return super.equals(obj);
    }
    NestData other = (NestData) obj;

    if (!getChunk()
        .equals(other.getChunk())) return false;
    if (!getExtraContents()
        .equals(other.getExtraContents())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHUNK_FIELD_NUMBER;
    hash = (53 * hash) + getChunk().hashCode();
    hash = (37 * hash) + EXTRA_CONTENTS_FIELD_NUMBER;
    hash = (53 * hash) + getExtraContents().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NestData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NestData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NestData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NestData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NestData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NestData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NestData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NestData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NestData)
      NestDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Nest.internal_static_NestData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Nest.internal_static_NestData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NestData.class, Builder.class);
    }

    // Construct using NestData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      chunk_ = com.google.protobuf.ByteString.EMPTY;

      extraContents_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Nest.internal_static_NestData_descriptor;
    }

    @Override
    public NestData getDefaultInstanceForType() {
      return NestData.getDefaultInstance();
    }

    @Override
    public NestData build() {
      NestData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NestData buildPartial() {
      NestData result = new NestData(this);
      result.chunk_ = chunk_;
      result.extraContents_ = extraContents_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NestData) {
        return mergeFrom((NestData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NestData other) {
      if (other == NestData.getDefaultInstance()) return this;
      if (other.getChunk() != com.google.protobuf.ByteString.EMPTY) {
        setChunk(other.getChunk());
      }
      if (!other.getExtraContents().isEmpty()) {
        extraContents_ = other.extraContents_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NestData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NestData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString chunk_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes chunk = 1;</code>
     * @return The chunk.
     */
    @Override
    public com.google.protobuf.ByteString getChunk() {
      return chunk_;
    }
    /**
     * <code>bytes chunk = 1;</code>
     * @param value The chunk to set.
     * @return This builder for chaining.
     */
    public Builder setChunk(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chunk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes chunk = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChunk() {
      
      chunk_ = getDefaultInstance().getChunk();
      onChanged();
      return this;
    }

    private Object extraContents_ = "";
    /**
     * <code>string extra_contents = 2;</code>
     * @return The extraContents.
     */
    public String getExtraContents() {
      Object ref = extraContents_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extraContents_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string extra_contents = 2;</code>
     * @return The bytes for extraContents.
     */
    public com.google.protobuf.ByteString
        getExtraContentsBytes() {
      Object ref = extraContents_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extraContents_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extra_contents = 2;</code>
     * @param value The extraContents to set.
     * @return This builder for chaining.
     */
    public Builder setExtraContents(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extraContents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extra_contents = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtraContents() {
      
      extraContents_ = getDefaultInstance().getExtraContents();
      onChanged();
      return this;
    }
    /**
     * <code>string extra_contents = 2;</code>
     * @param value The bytes for extraContents to set.
     * @return This builder for chaining.
     */
    public Builder setExtraContentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extraContents_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NestData)
  }

  // @@protoc_insertion_point(class_scope:NestData)
  private static final NestData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NestData();
  }

  public static NestData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NestData>
      PARSER = new com.google.protobuf.AbstractParser<NestData>() {
    @Override
    public NestData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NestData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NestData> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NestData> getParserForType() {
    return PARSER;
  }

  @Override
  public NestData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

