package com.clova.grpc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

/**
 * Protobuf type {@code NestRequest}
 */
public final class NestRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NestRequest)
    NestRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NestRequest.newBuilder() to construct.
  private NestRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NestRequest() {
    type_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new NestRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NestRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            NestConfig.Builder subBuilder = null;
            if (partCase_ == 2) {
              subBuilder = ((NestConfig) part_).toBuilder();
            }
            part_ =
                input.readMessage(NestConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((NestConfig) part_);
              part_ = subBuilder.buildPartial();
            }
            partCase_ = 2;
            break;
          }
          case 26: {
            NestData.Builder subBuilder = null;
            if (partCase_ == 3) {
              subBuilder = ((NestData) part_).toBuilder();
            }
            part_ =
                input.readMessage(NestData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((NestData) part_);
              part_ = subBuilder.buildPartial();
            }
            partCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Nest.internal_static_NestRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Nest.internal_static_NestRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NestRequest.class, Builder.class);
  }

  private int partCase_ = 0;
  private Object part_;
  public enum PartCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    CONFIG(2),
    DATA(3),
    PART_NOT_SET(0);
    private final int value;
    private PartCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static PartCase valueOf(int value) {
      return forNumber(value);
    }

    public static PartCase forNumber(int value) {
      switch (value) {
        case 2: return CONFIG;
        case 3: return DATA;
        case 0: return PART_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PartCase
  getPartCase() {
    return PartCase.forNumber(
        partCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.RequestType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.RequestType type = 1;</code>
   * @return The type.
   */
  @Override public RequestType getType() {
    @SuppressWarnings("deprecation")
    RequestType result = RequestType.valueOf(type_);
    return result == null ? RequestType.UNRECOGNIZED : result;
  }

  public static final int CONFIG_FIELD_NUMBER = 2;
  /**
   * <code>.NestConfig config = 2;</code>
   * @return Whether the config field is set.
   */
  @Override
  public boolean hasConfig() {
    return partCase_ == 2;
  }
  /**
   * <code>.NestConfig config = 2;</code>
   * @return The config.
   */
  @Override
  public NestConfig getConfig() {
    if (partCase_ == 2) {
       return (NestConfig) part_;
    }
    return NestConfig.getDefaultInstance();
  }
  /**
   * <code>.NestConfig config = 2;</code>
   */
  @Override
  public NestConfigOrBuilder getConfigOrBuilder() {
    if (partCase_ == 2) {
       return (NestConfig) part_;
    }
    return NestConfig.getDefaultInstance();
  }

  public static final int DATA_FIELD_NUMBER = 3;
  /**
   * <code>.NestData data = 3;</code>
   * @return Whether the data field is set.
   */
  @Override
  public boolean hasData() {
    return partCase_ == 3;
  }
  /**
   * <code>.NestData data = 3;</code>
   * @return The data.
   */
  @Override
  public NestData getData() {
    if (partCase_ == 3) {
       return (NestData) part_;
    }
    return NestData.getDefaultInstance();
  }
  /**
   * <code>.NestData data = 3;</code>
   */
  @Override
  public NestDataOrBuilder getDataOrBuilder() {
    if (partCase_ == 3) {
       return (NestData) part_;
    }
    return NestData.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != RequestType.CONFIG.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (partCase_ == 2) {
      output.writeMessage(2, (NestConfig) part_);
    }
    if (partCase_ == 3) {
      output.writeMessage(3, (NestData) part_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != RequestType.CONFIG.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (partCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (NestConfig) part_);
    }
    if (partCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (NestData) part_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NestRequest)) {
      return super.equals(obj);
    }
    NestRequest other = (NestRequest) obj;

    if (type_ != other.type_) return false;
    if (!getPartCase().equals(other.getPartCase())) return false;
    switch (partCase_) {
      case 2:
        if (!getConfig()
            .equals(other.getConfig())) return false;
        break;
      case 3:
        if (!getData()
            .equals(other.getData())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (partCase_) {
      case 2:
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getConfig().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NestRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NestRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NestRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NestRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NestRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NestRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NestRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NestRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NestRequest)
      NestRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Nest.internal_static_NestRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Nest.internal_static_NestRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NestRequest.class, Builder.class);
    }

    // Construct using NestRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      partCase_ = 0;
      part_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Nest.internal_static_NestRequest_descriptor;
    }

    @Override
    public NestRequest getDefaultInstanceForType() {
      return NestRequest.getDefaultInstance();
    }

    @Override
    public NestRequest build() {
      NestRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NestRequest buildPartial() {
      NestRequest result = new NestRequest(this);
      result.type_ = type_;
      if (partCase_ == 2) {
        if (configBuilder_ == null) {
          result.part_ = part_;
        } else {
          result.part_ = configBuilder_.build();
        }
      }
      if (partCase_ == 3) {
        if (dataBuilder_ == null) {
          result.part_ = part_;
        } else {
          result.part_ = dataBuilder_.build();
        }
      }
      result.partCase_ = partCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NestRequest) {
        return mergeFrom((NestRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NestRequest other) {
      if (other == NestRequest.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getPartCase()) {
        case CONFIG: {
          mergeConfig(other.getConfig());
          break;
        }
        case DATA: {
          mergeData(other.getData());
          break;
        }
        case PART_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NestRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NestRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int partCase_ = 0;
    private Object part_;
    public PartCase
        getPartCase() {
      return PartCase.forNumber(
          partCase_);
    }

    public Builder clearPart() {
      partCase_ = 0;
      part_ = null;
      onChanged();
      return this;
    }


    private int type_ = 0;
    /**
     * <code>.RequestType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.RequestType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.RequestType type = 1;</code>
     * @return The type.
     */
    @Override
    public RequestType getType() {
      @SuppressWarnings("deprecation")
      RequestType result = RequestType.valueOf(type_);
      return result == null ? RequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.RequestType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.RequestType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        NestConfig, NestConfig.Builder, NestConfigOrBuilder> configBuilder_;
    /**
     * <code>.NestConfig config = 2;</code>
     * @return Whether the config field is set.
     */
    @Override
    public boolean hasConfig() {
      return partCase_ == 2;
    }
    /**
     * <code>.NestConfig config = 2;</code>
     * @return The config.
     */
    @Override
    public NestConfig getConfig() {
      if (configBuilder_ == null) {
        if (partCase_ == 2) {
          return (NestConfig) part_;
        }
        return NestConfig.getDefaultInstance();
      } else {
        if (partCase_ == 2) {
          return configBuilder_.getMessage();
        }
        return NestConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.NestConfig config = 2;</code>
     */
    public Builder setConfig(NestConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        part_ = value;
        onChanged();
      } else {
        configBuilder_.setMessage(value);
      }
      partCase_ = 2;
      return this;
    }
    /**
     * <code>.NestConfig config = 2;</code>
     */
    public Builder setConfig(
        NestConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        part_ = builderForValue.build();
        onChanged();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      partCase_ = 2;
      return this;
    }
    /**
     * <code>.NestConfig config = 2;</code>
     */
    public Builder mergeConfig(NestConfig value) {
      if (configBuilder_ == null) {
        if (partCase_ == 2 &&
            part_ != NestConfig.getDefaultInstance()) {
          part_ = NestConfig.newBuilder((NestConfig) part_)
              .mergeFrom(value).buildPartial();
        } else {
          part_ = value;
        }
        onChanged();
      } else {
        if (partCase_ == 2) {
          configBuilder_.mergeFrom(value);
        }
        configBuilder_.setMessage(value);
      }
      partCase_ = 2;
      return this;
    }
    /**
     * <code>.NestConfig config = 2;</code>
     */
    public Builder clearConfig() {
      if (configBuilder_ == null) {
        if (partCase_ == 2) {
          partCase_ = 0;
          part_ = null;
          onChanged();
        }
      } else {
        if (partCase_ == 2) {
          partCase_ = 0;
          part_ = null;
        }
        configBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.NestConfig config = 2;</code>
     */
    public NestConfig.Builder getConfigBuilder() {
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.NestConfig config = 2;</code>
     */
    @Override
    public NestConfigOrBuilder getConfigOrBuilder() {
      if ((partCase_ == 2) && (configBuilder_ != null)) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        if (partCase_ == 2) {
          return (NestConfig) part_;
        }
        return NestConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.NestConfig config = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NestConfig, NestConfig.Builder, NestConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        if (!(partCase_ == 2)) {
          part_ = NestConfig.getDefaultInstance();
        }
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NestConfig, NestConfig.Builder, NestConfigOrBuilder>(
                (NestConfig) part_,
                getParentForChildren(),
                isClean());
        part_ = null;
      }
      partCase_ = 2;
      onChanged();;
      return configBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        NestData, NestData.Builder, NestDataOrBuilder> dataBuilder_;
    /**
     * <code>.NestData data = 3;</code>
     * @return Whether the data field is set.
     */
    @Override
    public boolean hasData() {
      return partCase_ == 3;
    }
    /**
     * <code>.NestData data = 3;</code>
     * @return The data.
     */
    @Override
    public NestData getData() {
      if (dataBuilder_ == null) {
        if (partCase_ == 3) {
          return (NestData) part_;
        }
        return NestData.getDefaultInstance();
      } else {
        if (partCase_ == 3) {
          return dataBuilder_.getMessage();
        }
        return NestData.getDefaultInstance();
      }
    }
    /**
     * <code>.NestData data = 3;</code>
     */
    public Builder setData(NestData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        part_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }
      partCase_ = 3;
      return this;
    }
    /**
     * <code>.NestData data = 3;</code>
     */
    public Builder setData(
        NestData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        part_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      partCase_ = 3;
      return this;
    }
    /**
     * <code>.NestData data = 3;</code>
     */
    public Builder mergeData(NestData value) {
      if (dataBuilder_ == null) {
        if (partCase_ == 3 &&
            part_ != NestData.getDefaultInstance()) {
          part_ = NestData.newBuilder((NestData) part_)
              .mergeFrom(value).buildPartial();
        } else {
          part_ = value;
        }
        onChanged();
      } else {
        if (partCase_ == 3) {
          dataBuilder_.mergeFrom(value);
        }
        dataBuilder_.setMessage(value);
      }
      partCase_ = 3;
      return this;
    }
    /**
     * <code>.NestData data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        if (partCase_ == 3) {
          partCase_ = 0;
          part_ = null;
          onChanged();
        }
      } else {
        if (partCase_ == 3) {
          partCase_ = 0;
          part_ = null;
        }
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.NestData data = 3;</code>
     */
    public NestData.Builder getDataBuilder() {
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.NestData data = 3;</code>
     */
    @Override
    public NestDataOrBuilder getDataOrBuilder() {
      if ((partCase_ == 3) && (dataBuilder_ != null)) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        if (partCase_ == 3) {
          return (NestData) part_;
        }
        return NestData.getDefaultInstance();
      }
    }
    /**
     * <code>.NestData data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NestData, NestData.Builder, NestDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        if (!(partCase_ == 3)) {
          part_ = NestData.getDefaultInstance();
        }
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NestData, NestData.Builder, NestDataOrBuilder>(
                (NestData) part_,
                getParentForChildren(),
                isClean());
        part_ = null;
      }
      partCase_ = 3;
      onChanged();;
      return dataBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NestRequest)
  }

  // @@protoc_insertion_point(class_scope:NestRequest)
  private static final NestRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NestRequest();
  }

  public static NestRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NestRequest>
      PARSER = new com.google.protobuf.AbstractParser<NestRequest>() {
    @Override
    public NestRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NestRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NestRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NestRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public NestRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

