package com.clova.grpc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

public interface NestConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NestConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string config = 1;</code>
   * @return The config.
   */
  String getConfig();
  /**
   * <code>string config = 1;</code>
   * @return The bytes for config.
   */
  com.google.protobuf.ByteString
      getConfigBytes();
}
