// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

public final class Nest {
  private Nest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnest.proto\032\031google/protobuf/any.proto\"" +
      "\034\n\nNestConfig\022\016\n\006config\030\001 \001(\t\"1\n\010NestDat" +
      "a\022\r\n\005chunk\030\001 \001(\014\022\026\n\016extra_contents\030\002 \001(\t" +
      "\"k\n\013NestRequest\022\032\n\004type\030\001 \001(\0162\014.RequestT" +
      "ype\022\035\n\006config\030\002 \001(\0132\013.NestConfigH\000\022\031\n\004da" +
      "ta\030\003 \001(\0132\t.NestDataH\000B\006\n\004part\" \n\014NestRes" +
      "ponse\022\020\n\010contents\030\001 \001(\t*#\n\013RequestType\022\n" +
      "\n\006CONFIG\020\000\022\010\n\004DATA\020\0012=\n\013NestService\022.\n\tr" +
      "ecognize\022\014.NestRequest\032\r.NestResponse\"\000(" +
      "\0010\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_NestConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NestConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestConfig_descriptor,
        new java.lang.String[] { "Config", });
    internal_static_NestData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NestData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestData_descriptor,
        new java.lang.String[] { "Chunk", "ExtraContents", });
    internal_static_NestRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestRequest_descriptor,
        new java.lang.String[] { "Type", "Config", "Data", "Part", });
    internal_static_NestResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestResponse_descriptor,
        new java.lang.String[] { "Contents", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
