// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

public interface NestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RequestType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.RequestType type = 1;</code>
   * @return The type.
   */
  RequestType getType();

  /**
   * <code>.NestConfig config = 2;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.NestConfig config = 2;</code>
   * @return The config.
   */
  NestConfig getConfig();
  /**
   * <code>.NestConfig config = 2;</code>
   */
  NestConfigOrBuilder getConfigOrBuilder();

  /**
   * <code>.NestData data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.NestData data = 3;</code>
   * @return The data.
   */
  NestData getData();
  /**
   * <code>.NestData data = 3;</code>
   */
  NestDataOrBuilder getDataOrBuilder();

  public NestRequest.PartCase getPartCase();
}
